### ISSUE TITLE
Yggdrasil协议有改动，KMCCC或将无法正版登录

### ISSUE THREAD

**Issue by hempflower** [MineStudio/KMCCC#15]
近期Yggdrasil发生了小改动，accesstoken格式向JWT过渡。这使得一部分以Guid方式存储at的启动器(例如BaKaXL)正版验证时出现了错误。    

相关资料:[https://wiki.vg/Authentication](https://wiki.vg/Authentication)     
相关代码: 
[https://github.com/MineStudio/KMCCC/blob/master/KMCCC.Shared/Authentication/AuthenticationInfo.cs#L28](https://github.com/MineStudio/KMCCC/blob/master/KMCCC.Shared/Authentication/AuthenticationInfo.cs#L28)

补救措施，使用字符串(String)来保存accesstoekn.

**Comment by RealHeart** [comment]
具体的实现方法是什么呢

**Comment by hempflower** [comment]
@RealHeart 
https://github.com/MineStudio/KMCCC/blob/master/KMCCC.Shared/Authentication/AuthenticationInfo.cs#L28
将AccessToken 的类型修改为String，同时修改相关代码。

**Comment by hempflower** [comment]
@RealHeart 
我对此问题尝试进行修复，这是修复版本:https://github.com/hempflower/KMCCC
希望你可以进行测试，如果没有问题，我将PR。

**Comment by RealHeart** [comment]
明天我试试。

**Comment by RealHeart** [comment]
> @RealHeart
> 我对此问题尝试进行修复，这是修复版本:https://github.com/hempflower/KMCCC
> 希望你可以进行测试，如果没有问题，我将PR。

正常登陆

**Comment by hempflower** [comment]
This issue has been fixed on a83131c .
