### ISSUE TITLE
kmccc可以更改正版登陆服务器的api吗

### ISSUE THREAD

**Issue by ruidps** [MineStudio/KMCCC#4]
如题，真在使用@to2mbn的agentlib-agent外加bs皮肤站实现外置登陆，若是用hmcl就可以直接加载编译的jar直接实现，若是使用c#是否更改api地址可以实现一样的功能，若是可以那kmccc可以直接实现吗？或是修改替换api字节码的功能也要在启动器实现？

**Comment by ZhaiSoul** [comment]
KMCCC能够设置JavaAgent，为AgentPath

**Comment by ruidps** [comment]
说的是加载给启动器的，而不是加载给游戏本体的，游戏本体直接采用forge加载

**Comment by ZhaiSoul** [comment]
能的，你在新建正版验证器的时候，是可以设置AuthServer 
详见https://github.com/MineStudio/KMCCC/blob/master/KMCCC.Shared/Authentication/Yggdrasil.cs

**Comment by ruidps** [comment]
还不是太理解这个函数，几个属性的格式是怎么样的呢？token可以直接赋值为null吗？验证服务器http://xxx.com/api/yggdrasil/这样可以吗？还是要到验证那层？
不是太理解token

**Comment by ZhaiSoul** [comment]
token是用于特殊验证用的，如果没有用到特殊验证就不需要
验证服务器地址取决于agentlib-agent中你的设置，一般就是http://xxx.com/api/
