### ISSUE TITLE
新版本工程提示缺失源文件

### ISSUE THREAD

**Issue by Nsiso** [MineStudio/KMCCC#5]
未能找到源文件“...\KMCCC-master\KMCCC.Shared\Modules\Minecraft\GameOptions.cs”。
未能找到源文件“...\KMCCC-master\KMCCC.Shared\Tools\MinecraftTools.cs”。
是忘记添加到Github了吗

**Comment by ZhaiSoul** [comment]
失误，昨晚更新脑袋短路，你可以先手动创建两个空cs来解决
这两个cs还没考虑好怎么写，所以没传上来
